# site settings
title: Σύλλογος Χρονομεριστών ΠΟΡΤΟ ΥΔΡΑ / PORTO HYDRA Timeshare Owners Association
google_analytics_id: UA-31340322-1
# url: "http://portohydra.time-share.gr"
shareaholic_app_id: 24300592
shareaholic_site_id: 36885dbbe02917b653d3e0344321da0b
# Get this from the url https://cse.google.com/cse/create/getcode?cx=003860276827165511839%3Az-jvfny0y24
# or the v1 codebase
google_search: 003860276827165511839:z-jvfny0y24
contactform_mailTo: portohydra@time-share.gr
webmaster_mail: svris@thinkit.gr
excerpt_separator: <!--more-->
page_size: 5

t: 
 el:
  company: "Σύλλογος Χρονομεριστών ΠΟΡΤΟ ΥΔΡΑ"
  search: "Αναζήτηση"
  findUsOn: "Βρείτε μας στο"
  readMore: "Διαβάστε περισσότερα"
  youNeedAdobe: "Εάν δεν μπορείτε να διαβάσετε τα .pdf αρχεία, χρειάζεται να κατεβάσετε τον Adobe Reader"
  downloadAdobeFrom: "είναι δωρεάν και τον κατεβάζετε από εδώ"
  pages: Σελίδες
  pagesFirst: πρώτη
  pagesPrevious: προηγούμενη
  pagesLast: τελευταία
  pagesNext: επόμενη
 en:
  company: "PORTO HYDRA Timeshare Owners Association"
  search: "Search"
  findUsOn: "Find us on"
  readMore: "Read more"
  youNeedAdobe: "If you can't open the .pdf files, you will need to download and install Adobe Reader"
  downloadAdobeFrom: "this is free application and you can download from here"
  pages: Pages
  pagesFirst: first
  pagesPrevious: previous
  pagesLast: last
  pagesNext: next

gems:
  - jekyll-redirect-from
  - jekyll-paginate

# standard jekyll configuration
exclude:
- Gemfile
- Gemfile.lock
- README.md
- "*.bat"
- CNAME
- "*.sln"
- "*.suo"
- CleanupCss.js