# site settings
title: Σύλλογος Χρονομεριστών ΠΟΡΤΟ ΥΔΡΑ / PORTO HYDRA Timeshare Owners Association
google_analytics_id: UA-31340322-1
# url: "http://portohydra.time-share.gr"
shareaholic_app_id: 24300592
shareaholic_site_id: 36885dbbe02917b653d3e0344321da0b
# Get this from the url https://cse.google.com/cse/create/getcode?cx=003860276827165511839%3Az-jvfny0y24
# or the v1 codebase
google_search: 003860276827165511839:z-jvfny0y24

t: 
 el:
  company: "Σύλλογος Χρονομεριστών ΠΟΡΤΟ ΥΔΡΑ"
  search: "Αναζήτηση"
  findUsOn: "Βρείτε μας στο"
 en:
  company: "PORTO HYDRA Timeshare Owners Association"
  search: "Search"
  findUsOn: "Find us on"

gems:
  - jekyll-redirect-from

# standard jekyll configuration
exclude:
- Gemfile
- Gemfile.lock
- README.md
- "*.bat"
- CNAME
- "*.sln"
- "*.suo"